apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: fib-com-tls
spec:
  secretName: fib-com
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fib.archisdi.me
  dnsNames:
    - fib.archisdi.me
    # add www here
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - fib.archisdi.me
          # add www here
