apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: fib-com-tls
spec:
  secretName: fib-com
  issuerRef:
    issuer: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fib.archisdi.me
  dnsNames:
    - fib.archisdi.me
    # add www here
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - fib.archisdi.me
          # add www here
